#################################
#   Site-specifc interactions   #
#################################

# This script will look in the two sets of chromosome conformation data produced by the Meyer lab (2015 and 2017) and export heatmaps
# that show interaction frequency between a group of regions on the genome. 

# Chromosome conformation data has already been processed using the homebrew pipeline to produce a list of every interaction mapped to 
# their fragment ends.

# Required inputs
#A-Bed file with a list of regions of interest. (Cols: 1-chr, 2-position start, 3-position end, 4-name) 
#B-binsize
#C-output directory

#Example input for NYU HPC:
##Rscript ~/worms/scripts/site_specifc_interactions.R /scratch/cgsb/ercan/Defined_regions/rex_sites.bed 10000 /scratch/mrp420/heatmap/ > outputFile_1.Rout 2>&1

#STILL WORKING ON:
# AUTOSOMES
# RANDOM CONTROL/MEAN (MAYBE PUT AT BEGINNING). cAN USE IT WITH AN IF STATEMENT
# Make relative to whole genome
# 2015 datasets

#Arguments reported to ouptut file.
print('Script started')
Sys.time()
args <- commandArgs(trailingOnly=TRUE)
print(paste0('These are the args:',args))
query_region<-args

#Make sure correct dependencies are loaded and installed
if (!require("gplots")) {
  install.packages("gplots", dependencies = TRUE)
  library(gplots)
}

if (!require("RColorBrewer")) {
install.packages('RColorBrewer')
library(RColorBrewer)
}

if (!require("viridis")) {
  install.packages("viridis")
  library(viridis)
}


#Test inputs - used for troubleshooting the script
#query_region<-as.data.frame(c('/scratch/cgsb/ercan/Defined_regions/rex_sites.bed',10000, '~/Desktop'), stringsAsFactors = F)

#Read in the data files - these are the list of fends from the meyer data. These directories are avaliable to members of the Ercan lab.  
#The equivalent files can be generated by running homebrew piepline on the meyer data.
N2B12015_intra<-read.table('/scratch/cgsb/ercan/GEO/2015_meyer/interactions/N2B12015_intra_fends', stringsAsFactors=F)
N2B22015_intra<-read.table('/scratch/cgsb/ercan/GEO/2015_meyer/interactions/N2B22015_intra_fends', stringsAsFactors=F)
SDC2B12015_intra<-read.table('/scratch/cgsb/ercan/GEO/2015_meyer/interactions/SDC2B12015_intra_fends', stringsAsFactors=F)
SDC2B22015_intra<-read.table('/scratch/cgsb/ercan/GEO/2015_meyer/interactions/SDC2B22015_intra_fends', stringsAsFactors=F)

N2B1_intra<-read.table('/scratch/cgsb/ercan/GEO/2017_meyer/interactions/N2B1_intra_fends', stringsAsFactors=F)
N2B2_intra<-read.table('/scratch/cgsb/ercan/GEO/2017_meyer/interactions/N2B2_intra_fends', stringsAsFactors=F)
SDC2B1_intra<-read.table('/scratch/cgsb/ercan/GEO/2017_meyer/interactions/SDC2B1_intra_fends', stringsAsFactors=F)
SDC2B2_intra<-read.table('/scratch/cgsb/ercan/GEO/2017_meyer/interactions/SDC2B2_intra_fends', stringsAsFactors=F)

N2B1_inter<-read.table('/scratch/cgsb/ercan/GEO/2017_meyer/interactions/N2B1_inter_fends', stringsAsFactors=F)
N2B2_inter<-read.table('/scratch/cgsb/ercan/GEO/2017_meyer/interactions/N2B2_inter_fends', stringsAsFactors=F)
SDC2B1_inter<-read.table('/scratch/cgsb/ercan/GEO/2017_meyer/interactions/SDC2B1_inter_fends', stringsAsFactors=F)
SDC2B2_inter<-read.table('/scratch/cgsb/ercan/GEO/2017_meyer/interactions/SDC2B2_inter_fends', stringsAsFactors=F)

N2B12015_inter<-read.table('/scratch/cgsb/ercan/GEO/2015_meyer/interactions/N2B12015_inter_fends', stringsAsFactors=F)
N2B22015_inter<-read.table('/scratch/cgsb/ercan/GEO/2015_meyer/interactions/N2B22015_inter_fends', stringsAsFactors=F)
SDC2B12015_inter<-read.table('/scratch/cgsb/ercan/GEO/2015_meyer/interactions/SDC2B12015_inter_fends', stringsAsFactors=F)
SDC2B22015_inter<-read.table('/scratch/cgsb/ercan/GEO/2015_meyer/interactions/SDC2B22015_inter_fends', stringsAsFactors=F)
print('Files read in succesfully')
Sys.time()

N2B1<-rbind(N2B1_intra,N2B1_inter)
N2B2<-rbind(N2B2_intra,N2B2_inter)
SDC2B1<-rbind(SDC2B1_intra,SDC2B1_inter)
SDC2B2<-rbind(SDC2B2_intra,SDC2B2_inter)
N2B12015<-rbind(N2B12015_intra,N2B12015_inter)
N2B22015<-rbind(N2B22015_intra,N2B22015_inter)
SDC2B12015<-rbind(SDC2B12015_intra,SDC2B12015_inter)
SDC2B22015<-rbind(SDC2B22015_intra,SDC2B22015_inter)

query_region<-list(c('/scratch/cgsb/ercan/Defined_regions/rex_sites.bed',20000,'/scratch/mrp420/heatmap'))
dir.create(query_region[[1]][3])

#Trial inputs
#N2B1_intra<-read.table('~/Desktop/N2B1_intra_fends', stringsAsFactors=F)
#N2B1_inter<-read.table('~/Desktop/N2B1_inter_fends', stringsAsFactors=F)
#N2B2_intra<-read.table('~/Desktop/N2B2_intra_fends', stringsAsFactors=F)
#N2B2_inter<-read.table('~/Desktop/N2B2_inter_fends', stringsAsFactors=F)
#SDC2B1_intra<-read.table('~/Desktop/SDC2B1_intra_fends', stringsAsFactors=F)
#SDC2B1_inter<-read.table('~/Desktop/SDC2B1_inter_fends', stringsAsFactors=F)

#N2B1<-rbind(N2B1_intra,N2B1_inter)
#N2B2<-rbind(N2B2_intra,N2B2_inter)
#SDC2B1<-rbind(SDC2B1_intra,SDC2B1_inter)

#regions_of_interest<-read.table('~/Desktop/rex_sites.bed', stringsAsFactors=F)
#query_region<-list(c('~/Desktop/rex_sites.bed',20000,'~/Desktop/heatmaps/'))
#dir.create(query_region[[1]][3])

#Read in the regions that we are really interested in
regions_of_interest<-read.table(query_region[[1]][1], stringsAsFactors=F)
print('Input files opened')

#Define the regions of interest based on the binsize. 
midpoints<-((as.numeric(regions_of_interest[,3])-(as.numeric(regions_of_interest[,2])))/2+as.numeric(regions_of_interest[,2]))
left_boundaries<-midpoints-(as.numeric(query_region[[1]][2])/2)
right_boundaries<-midpoints+(as.numeric(query_region[[1]][2])/2)

my_bed_file<-data.frame(regions_of_interest[,1],left_boundaries,right_boundaries, stringsAsFactors=F)
####NEED TO MODIFY THIS SO THAT THE SPECIFIC FILE INTREREST CAN HANDLE MULTIPLE CHROMOMOSOMES
my_bed_file_ordered<-my_bed_file[(order(my_bed_file[,2])),]

#Function to subset my fend files e to specifically those that are of interest to you
fend_hits<-function(bed,fends_table){
left_hits<-which(fends_table[,1]==as.character(bed[1])&fends_table[,2]>as.numeric(bed[2])&fends_table[,2]<as.numeric(bed[3]))
right_hits<-which(fends_table[,3]==as.character(bed[1])&fends_table[,4]>as.numeric(bed[2])&fends_table[,4]<as.numeric(bed[3]))
cross_hits<-list(left_hits,right_hits)
return(cross_hits)
}

#Function to take my subsetted fend file and turn it into a matrix of regions of interest with counts
fend_matrix<-function(my_bed_file,fends_table,interactions){
outputmatrix<-matrix(0,nrow(regions_of_interest),nrow(regions_of_interest))
for(j in 1:nrow(my_bed_file) ){
  for(i in 1:nrow(my_bed_file) ){
    count1<-length(which(fends_table[interactions[[j]][[1]],][,3]==as.character(my_bed_file[i,1])&fends_table[interactions[[j]][[1]],][,4]>as.numeric(my_bed_file[i,2])&fends_table[interactions[[j]][[1]],][,4]<as.numeric(my_bed_file[i,3])))
    count2<-length(which(fends_table[interactions[[j]][[2]],][,1]==as.character(my_bed_file[i,1])&fends_table[interactions[[j]][[2]],][,2]>as.numeric(my_bed_file[i,2])&fends_table[interactions[[j]][[2]],][,2]<as.numeric(my_bed_file[i,3])))
    count<-count1+count2
    outputmatrix[i,j]<-outputmatrix[i,j]+count
  }
  if(j %% 10==0) {
  print(j)}}
return(outputmatrix)
}

#Run it for each dataset
interactions<-apply(my_bed_file,1,fend_hits,fends_table=N2B1)
N2B1_native<-fend_matrix(my_bed_file,fends_table=N2B1,interactions)
interactions<-apply(my_bed_file_ordered,1,fend_hits,fends_table=N2B1)
N2B1_ordered<-fend_matrix(my_bed_file_ordered,fends_table=N2B1,interactions)
print('N2B1 COUNTED')
Sys.time()

interactions<-apply(my_bed_file,1,fend_hits,fends_table=N2B2)
N2B2_native<-fend_matrix(my_bed_file,fends_table=N2B2,interactions)
interactions<-apply(my_bed_file_ordered,1,fend_hits,fends_table=N2B2)
N2B2_ordered<-fend_matrix(my_bed_file_ordered,fends_table=N2B2,interactions)
print('N2B2 COUNTED')
Sys.time()

interactions<-apply(my_bed_file,1,fend_hits,fends_table=SDC2B1)
SDC2B1_native<-fend_matrix(my_bed_file,fends_table=SDC2B1,interactions)
interactions<-apply(my_bed_file_ordered,1,fend_hits,fends_table=SDC2B1)
SDC2B1_ordered<-fend_matrix(my_bed_file_ordered,fends_table=SDC2B1,interactions)
print('SDC2B1 COUNTED')
Sys.time()

interactions<-apply(my_bed_file,1,fend_hits,fends_table=SDC2B2)
SDC2B2_native<-fend_matrix(my_bed_file,fends_table=SDC2B2,interactions)
interactions<-apply(my_bed_file_ordered,1,fend_hits,fends_table=SDC2B2)
SDC2B2_ordered<-fend_matrix(my_bed_file_ordered,fends_table=SDC2B2,interactions)
print('SDC2B2 COUNTED')
Sys.time()

#Ensure that the matrices have the correct column and row names

colnames(N2B1_ordered)<-regions_of_interest[(order(my_bed_file[,2])),4]
row.names(N2B1_ordered)<-regions_of_interest[(order(my_bed_file[,2])),4]
colnames(N2B2_ordered)<-regions_of_interest[(order(my_bed_file[,2])),4]
row.names(N2B2_ordered)<-regions_of_interest[(order(my_bed_file[,2])),4]
colnames(SDC2B1_ordered)<-regions_of_interest[(order(my_bed_file[,2])),4]
row.names(SDC2B1_ordered)<-regions_of_interest[(order(my_bed_file[,2])),4]
colnames(SDC2B2_ordered)<-regions_of_interest[(order(my_bed_file[,2])),4]
row.names(SDC2B2_ordered)<-regions_of_interest[(order(my_bed_file[,2])),4]

colnames(N2B1_native)<-regions_of_interest[,4]
row.names(N2B1_native)<-regions_of_interest[,4]
colnames(N2B2_native)<-regions_of_interest[,4]
row.names(N2B2_native)<-regions_of_interest[,4]
colnames(SDC2B1_native)<-regions_of_interest[,4]
row.names(SDC2B1_native)<-regions_of_interest[,4]
colnames(SDC2B2_native)<-regions_of_interest[,4]
row.names(SDC2B2_native)<-regions_of_interest[,4]

print('Matrices made')
Sys.time()

#For loop cycles through each dataset and outputs heatmaps for each individually
datasets<-c('N2B1_native','N2B2_native','SDC2B1_native','SDC2B2_native','N2B1_ordered','N2B2_ordered','SDC2B1_ordered','SDC2B2_ordered')

for (i in 1:length(datasets)){
outputmatrix<-get(datasets[i])
#Outputnames
output_key<-paste0(datasets[i],'_',query_region[[1]][2],'bp')
#Log transformation
positives<-which(outputmatrix>0)
outputmatrix_log10<-outputmatrix
outputmatrix_log10[positives]<-log10(outputmatrix[positives])

#Plot the data
pdf(paste0(query_region[[1]][3],'/',output_key,'.pdf'))
heatmap.2(outputmatrix,dendrogram="none", Rowv=NA, Colv=NA,trace="none",density.info="none",
          key=TRUE,key.xlab="interaction (Z-score)",key.title = NA,
          key.ylab=NULL, col = viridis(100), margins=c(5,10), scale="column", lhei=c(1,4), lwid=c(1,4), keysize=0.1, key.par = list(cex=0.75), main=paste0(' interaction score \n',output_key) )
dev.off()
#Plot the data following log10 trasnformation
pdf(paste0(query_region[[1]][3],'/',output_key,'_log10.pdf'))
heatmap.2(outputmatrix_log10,dendrogram="none", Rowv=NA, Colv=NA,trace="none",density.info="none",
          key=TRUE,key.xlab="interaction (Z-score)",key.title = NA,
          key.ylab=NULL, col = viridis(100), margins=c(5,10), lhei=c(1,4), lwid=c(1,4), keysize=0.1, key.par = list(cex=0.75), main=paste0('log10 interaction score \n',output_key) )
dev.off()
}
print('Each replicate is plotted')
Sys.time()


###Aggregate datasets and compare between them for ranked datasets

#Need to normalise dataset to total counts
N2B1_native_proportional<-N2B1_native/nrow(N2B1)
N2B2_native_proportional<-N2B2_native/nrow(N2B2)
SDC2B1_native_proportional<-SDC2B1_native/nrow(SDC2B1)
SDC2B2_native_proportional<-SDC2B2_native/nrow(SDC2B2)

#Merge datasets
N2_native_mean_norm<-((N2B1_native_proportional+N2B2_native_proportional)/2)/(sum(N2B1_native_proportional+N2B2_native_proportional)/2)
SDC2_native_mean_norm<-((SDC2B1_native_proportional+SDC2B2_native_proportional)/2)/(sum(SDC2B1_native_proportional+SDC2B2_native_proportional)/2)

outputmatrix_ratio<-(SDC2_native_mean_norm/N2_native_mean_norm)
outputmatrix_ratio[is.na(outputmatrix_ratio)]<-0
outputmatrix<-log2(outputmatrix_ratio)
outputmatrix[which(outputmatrix=='-Inf')]<-0
outputmatrix[which(outputmatrix=='Inf')]<-0

#Log transformation
positives<-which(outputmatrix>0)
outputmatrix_log10<-outputmatrix
outputmatrix_log10[positives]<-log10(outputmatrix[positives])

#Plot the data
pdf(paste0(query_region[[1]][3],'/logratio_byrank.pdf'))
heatmap.2(outputmatrix,dendrogram="none", Rowv=NA, Colv=NA,trace="none",density.info="none",
          key=TRUE,key.xlab="interaction (Z-score)",key.title = NA,
          key.ylab=NULL, col = viridis(69), margins=c(5,10), scale="column", lhei=c(1,4), lwid=c(1,4), keysize=0.1, key.par = list(cex=0.75), main=paste0(' interaction score by rank \n log2(SDC2/N2)' ))
dev.off()
#Plot the data following log10 trasnformation
pdf(paste0(query_region[[1]][3],'/log10_logratio_byrank.pdf'))
heatmap.2(outputmatrix_log10,dendrogram="none", Rowv=NA, Colv=NA,trace="none",density.info="none",
          key=TRUE,key.xlab="interaction (Z-score)",key.title = NA,
          key.ylab=NULL, col = viridis(34), margins=c(5,10), lhei=c(1,4), lwid=c(1,4), keysize=0.1, key.par = list(cex=0.75), main=paste0('log10 interaction score by rank \n log2(SDC2/N2)') )
dev.off()


###Aggregate datasets and compare between them for ordered datasets

#Need to normalise dataset to total counts
N2B1_ordered_proportional<-N2B1_ordered/nrow(N2B1)
N2B2_ordered_proportional<-N2B2_ordered/nrow(N2B2)
SDC2B1_ordered_proportional<-SDC2B1_ordered/nrow(SDC2B1)
SDC2B2_ordered_proportional<-SDC2B2_ordered/nrow(SDC2B2)

#Merge datasets
N2_ordered_mean_norm<-((N2B1_ordered_proportional+N2B2_ordered_proportional)/2)/(sum(N2B1_ordered_proportional+N2B2_ordered_proportional)/2)
SDC2_ordered_mean_norm<-((SDC2B1_ordered_proportional+SDC2B2_ordered_proportional)/2)/(sum(SDC2B1_ordered_proportional+SDC2B2_ordered_proportional)/2)

outputmatrix_ratio<-(SDC2_ordered_mean_norm/N2_ordered_mean_norm)
outputmatrix_ratio[is.na(outputmatrix_ratio)]<-0
outputmatrix<-log2(outputmatrix_ratio)
outputmatrix[which(outputmatrix=='-Inf')]<-0
outputmatrix[which(outputmatrix=='Inf')]<-0

#Log transformation
positives<-which(outputmatrix>0)
outputmatrix_log10<-outputmatrix
outputmatrix_log10[positives]<-log10(outputmatrix[positives])

#Plot the data
pdf(paste0(query_region[[1]][3],'/logratio_byorder.pdf'))
heatmap.2(outputmatrix,dendrogram="none", Rowv=NA, Colv=NA,trace="none",density.info="none",
          key=TRUE,key.xlab="interaction (Z-score)",key.title = NA,
          key.ylab=NULL, col = viridis(69), margins=c(5,10), scale="column", lhei=c(1,4), lwid=c(1,4), keysize=0.1, key.par = list(cex=0.75), main=paste0(' interaction score by order \n log2(SDC2/N2)' ))
dev.off()
#Plot the data following log10 trasnformation
pdf(paste0(query_region[[1]][3],'/log10_logratio_byorder.pdf'))
heatmap.2(outputmatrix_log10,dendrogram="none", Rowv=NA, Colv=NA,trace="none",density.info="none",
          key=TRUE,key.xlab="interaction (Z-score)",key.title = NA,
          key.ylab=NULL, col = viridis(34), margins=c(5,10), lhei=c(1,4), lwid=c(1,4), keysize=0.1, key.par = list(cex=0.75), main=paste0('log10 interaction score by order \n log2(SDC2/N2)') )
dev.off()

print('Aggregated datasets and log2ratios')
Sys.time()



###How much is this just driven by proximity?

#First graph according to the input order
#Create empty matrix and output key
outputmatrix<-matrix(0,nrow(regions_of_interest),nrow(regions_of_interest))
output_key<-paste0(query_region[[1]][2],'bp')
#Measure distance between eah point
for(j in 1:length(midpoints)) {
  for(i in 1:length(midpoints)) {
        outputmatrix[i,j]<-abs(midpoints[i]-midpoints[j])
    }}
#Add the row names
colnames(outputmatrix)<-regions_of_interest[,4]
row.names(outputmatrix)<-regions_of_interest[,4]
#Save to specifc matrix
outputmatrix_dist<-outputmatrix
pdf(paste0(query_region[[1]][3],'/',output_key,'_distance_by_rank.pdf'))
heatmap.2(outputmatrix_dist,dendrogram="none", Rowv=NA, Colv=NA,trace="none",density.info="none",
          key=TRUE,key.xlab="distance (Z-score)",key.title = NA,
          key.ylab=NULL, col = magma(50), scale="column", margins=c(5,10), lhei=c(1,4), lwid=c(1,4), keysize=0.1, key.par = list(cex=0.75), main='Distance between sites\n- ordered by rank' )
dev.off()

#Second graph according to the positional order
#Create empty matrix and output key
position<-(my_bed_file_ordered[,3]+my_bed_file_ordered[,2])/2
outputmatrix<-matrix(0,nrow(regions_of_interest),nrow(regions_of_interest))
output_key<-paste0(query_region[[1]][2],'bp')
#Measure distance between eah point
for(j in 1:length(position)) {
  for(i in 1:length(position)) {
    outputmatrix[i,j]<-abs(position[i]-position[j])
  }}
#Add the row names
colnames(outputmatrix)<-regions_of_interest[,4]
row.names(outputmatrix)<-regions_of_interest[,4]
#Save to specifc matrix
outputmatrix_distbypos<-outputmatrix
pdf(paste0(query_region[[1]][3],'/',output_key,'_distance_by_position.pdf'))
heatmap.2(outputmatrix_distbypos,dendrogram="none", Rowv=NA, Colv=NA,trace="none",density.info="none",
          key=TRUE,key.xlab="distance (Z-score)",key.title = NA,
          key.ylab=NULL, col = magma(50), scale="column", margins=c(5,10), lhei=c(1,4), lwid=c(1,4), keysize=0.1, key.par = list(cex=0.75), main='Distance between sites\n- ordered by position' )
dev.off()

print('Distance plots have been plotted')
Sys.time()

#Distribution of sites
pdf('~/Desktop/heatmaps/rex_site_distribution.pdf')
point_diff<-matrix(0,length(midpoints)-1,1)

reorderkey<-order(midpoints)

for(i in 1:length(midpoints)-1){
  point_diff[i,]<-my_bed_file_ordered[i+1,2]-my_bed_file_ordered[i,2]
}

par(mfrow=c(2,2))
plot(midpoints[reorderkey],matrix(1,1,length(midpoints)), xlab='Chr Position', yaxt='n', ylab='', main ='Rex positions on ChrX')
plot(midpoints[reorderkey],matrix(1:length(midpoints),1,length(midpoints)), ylab='Rex site', xlab='Chr Position', main ='Rex positions on ChrX')
plot(point_diff,xlab='Rex site pair', ylab='Distance between adjacent rex sites', main ='Distance between rex sites')
plot(log10(point_diff),xlab='Rex site pair', ylab='log10(Distance between adjacent rex sites)', main ='Distance between rex sites')

dev.off()

print('Site distribution plotted')
Sys.time()

print('All done! Woop woop!')
